#!/usr/bin/python3
# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Qt/myst/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import json
import requests
from PyQt5.QtWidgets import QLineEdit,QTreeWidget, QTreeWidgetItem,QListWidget,QListWidgetItem
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QThread,pyqtSignal


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1281, 805)
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.listWidget = QtWidgets.QListWidget(self.splitter)
        self.listWidget.setIconSize(QtCore.QSize(300, 300))
        self.listWidget.setResizeMode(QtWidgets.QListView.Adjust)
        self.listWidget.setViewMode(QtWidgets.QListView.IconMode)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1281, 20))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.splitter.setStretchFactor(1, 4)
        self.lineEdit.textChanged.connect(self.search)



        r=requests.get('http://172.96.193.223/category.php')

        json_array = r.json()

        store_list = []

        topstr=''

        for item in json_array:
            store_details = {'id':None,'cname':None, 'sname':None}
            store_details['id'] = item['id']

            store_details['cname'] = item['cname']
            
            if topstr!=item['cname']:
                topstr=item['cname']
                l1=QTreeWidgetItem()
                l1.setText(0,topstr)
                
                self.treeWidget.addTopLevelItem(l1)
            

            store_details['sname'] = item['sname']
            child=QTreeWidgetItem()
            child.setText(0,item['sname'])
            l1.addChild(child)
            l1.setExpanded(True)
            store_list.append(store_details)


        self.search('')
              

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Store"))
        self.groupBox.setTitle(_translate("MainWindow", "Category"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Search"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Detail"))

    def slotAdd(self,item):
        self.listWidget.addItem(item)

    def search(self,str):
        self.listWidget.clear()

        self.thread=Worker(None,str)
        self.thread.sinOut.connect(self.slotAdd)
        self.thread.start()


class Worker(QThread):
    sinOut = pyqtSignal([QListWidgetItem])

    def __init__(self,parent=None,str=''):
        super(Worker,self).__init__(parent)
        self.str=str
      
        
    def run(self):

        r=requests.get('http://172.96.193.223/product.php?key='+self.str)



        json_array = r.json()

        store_list = []

        for item in json_array:
            store_details = {'id':None,'name':None, 'cid':None,'images':None,'tags':None,'spec':None,'price':None}
            store_details['id'] = item['id']
            store_details['name'] = item['name']
            store_details['cid'] = item['cid']
            store_details['images'] = item['images']
            store_details['tags'] = item['tags']
            store_details['spec'] = item['spec']
            store_details['price'] = item['price']
            store_list.append(store_details) 

            pixmap=QtGui.QPixmap()
            pixmap.loadFromData(requests.get('http://172.96.193.223/thumbnail/'+item['images']).content)
            icon=QtGui.QIcon(pixmap)
            itm=QListWidgetItem(icon,item['name'])

            self.sinOut.emit(itm)



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
