#!/usr/bin/python3

# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'store.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import json
import requests
from PyQt5.QtWidgets import QLineEdit,QTreeWidget, QTreeWidgetItem,QTableWidget,QTableWidgetItem


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setFamily("WenQuanYi Micro Hei")
        font.setPointSize(12)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.groupBox = QtWidgets.QGroupBox(self.splitter)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lineEdit = QtWidgets.QLineEdit(self.groupBox)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout.addWidget(self.lineEdit)
        self.treeWidget = QtWidgets.QTreeWidget(self.groupBox)
        self.treeWidget.setObjectName("treeWidget")
        self.verticalLayout.addWidget(self.treeWidget)
        self.tableWidget = QtWidgets.QTableWidget(self.splitter)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.splitter.setStretchFactor(1, 4)
        self.lineEdit.textChanged.connect(self.search)

        r=requests.get('http://172.96.193.223/category.php')

        json_array = r.json()

        store_list = []

        topstr=''

        for item in json_array:
            store_details = {'id':None,'cname':None, 'sname':None}
            store_details['id'] = item['id']

            store_details['cname'] = item['cname']
            
            if topstr!=item['cname']:
                topstr=item['cname']
                l1=QTreeWidgetItem()
                l1.setText(0,topstr)
                
                self.treeWidget.addTopLevelItem(l1)
            

            store_details['sname'] = item['sname']
            child=QTreeWidgetItem()
            child.setText(0,item['sname'])
            l1.addChild(child)
            l1.setExpanded(True)
            store_list.append(store_details)

        self.search('')

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def search(self,str):
        r=requests.get('http://172.96.193.223/product.php?key='+str)
        #print(r.status_code)

        json_array = r.json()

        store_list = []

        for item in json_array:
            store_details = {'id':None,'name':None, 'cid':None,'images':None,'tags':None,'spec':None,'price':None}
            store_details['id'] = item['id']
            store_details['name'] = item['name']
            store_details['cid'] = item['cid']
            store_details['images'] = item['images']
            store_details['tags'] = item['tags']
            store_details['spec'] = item['spec']
            store_details['price'] = item['price']
            store_list.append(store_details)

        self.tableWidget.setRowCount(len(store_list))
        self.tableWidget.setColumnCount(7)
        self.tableWidget.setColumnWidth(1,300)
        head=['编号','商品名称','分类','图片','标签','规格','单价']
        self.tableWidget.setHorizontalHeaderLabels(head)
        j=0
        for i in store_list:
            self.tableWidget.setItem(j,0, QTableWidgetItem(i['id']))
            self.tableWidget.setItem(j,1, QTableWidgetItem(i['name']))
            self.tableWidget.setItem(j,2, QTableWidgetItem(i['cid']))
            self.tableWidget.setItem(j,3, QTableWidgetItem(i['images']))
            self.tableWidget.setItem(j,4, QTableWidgetItem(i['tags']))
            self.tableWidget.setItem(j,5, QTableWidgetItem(i['spec']))
            self.tableWidget.setItem(j,6, QTableWidgetItem(i['price']))
            j=j+1



    def retranslateUi(self, MainWindow):

        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "商品管理系统"))
        self.groupBox.setTitle(_translate("MainWindow", "搜索"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "全部分类"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
